/blurr/cmd_wrench:
    type: geometry_msgs/Wrench
    x:
        min: -40
        max: 40
        to: force.x
    y:
        min: -40
        max: 40
        to: force.y
    z:
        min: -40
        max: 40
        to: force.z
    roll:
        min: -40
        max: 40
        to: torque.x
    pitch:
        min: -40
        max: 40
        to: torque.y
    yaw:
        min: -40
        max: 40
        to: torque.z
/blurr/cmd_tilt:
    type: std_msgs/Float32
    angle:
        min: -pi/3
        max: pi/3
/blurr/cmd_light:
    type: std_msgs/Float32
    intensity:
        min: 0.
        max: 1.
        default: 0.
